docs/class-diagram.puml
=> added Presentation and Rating to class diagram

.env.example, package-lock.json, package.json, src/app.module.ts, src/auth/auth.controller.ts, src/auth/auth.module.ts, src/auth/auth.service.ts, src/auth/authsch.strategy.ts, src/users/users.module.ts
Authsch login working.
Closes #15
=> Authsch implemented

.vscode/launch.json
Pressing F5 will build and start the server (with debug breakpoints enabled)
=> Add vscode launch config

src/auth/auth.controller.ts, src/current-user.decorator.ts, src/users/users.controller.ts
1. 3f76999 I added a `@CurrentUser` decorator, that returns the value of `req.user`
2. 40b527f Replaced all `req.user` calls with `CurrentUser` calls.
3. f0e1ddf I added a new route, get /auth/me that validates the JWT token
Please squash and merge :rocket:
=> Add CurrentUser decorator

.eslintrc.js, .github/workflows/nodejs.yml, linter.tsconfig.json, mocks/@nestjs/passport/index.ts, mocks/@prisma/client/index.ts, package.json, src/auth/auth.controller.spec.ts, src/auth/auth.service.ts, src/consultations/consultations.controller.spec.ts, src/consultations/consultations.service.spec.ts, src/consultations/rating.service.spec.ts, src/env.spec.ts, src/groups/groups.controller.spec.ts, src/groups/groups.service.spec.ts, src/subject/subject.controller.spec.ts, src/subject/subject.service.spec.ts, src/users/users.controller.spec.ts, src/users/users.service.spec.ts
- Fix imports are not working in `src/**/*.spec.ts` files
- Fix eslint prettier integration
- Configure eslint to run on test files as well
- Force mock prisma and passport modules to avoid side effects
- Write tests to verify database and passport modules are mocked
- Add integration test for JWT token creation
- Add integration test for active vulnerability: _users can change anyone's authSchId_ in [userController.update](https://github.com/kir-dev/konzisite-api/blob/37f58498803b8e0423eae5b1f998ddc94272cb37/src/users/users.controller.ts#L49)
- Create github workflow to check code quality on pull requests
=> Initialize unit and integration tests and create github CI

src/consultations/rating.service.ts
=> Implement rating service

prisma/schema.prisma, src/consultations/consultations.controller.ts, src/consultations/consultations.service.ts, src/consultations/dto/ConsultationEntity.dto.ts, src/consultations/dto/ConsultationPreview.dto.ts, src/consultations/dto/CreateConsultation.dto.ts, src/consultations/dto/CreateRating.dto.ts, src/consultations/dto/UpdateConsultation.dto.ts, src/consultations/presentation.service.ts, src/consultations/rating.service.ts, src/groups/dto/GroupDetails.dto.ts, src/groups/dto/GroupEntity.dto.ts, src/groups/dto/GroupPreview.dto.ts, src/groups/groups.controller.ts, src/subject/dto/SubjectEntity.dto.ts, src/users/dto/UserEntity.dto.ts
- Copied the DTOs from the frontend project
- implemented the consultation CRUD service functions. Create and update methods create or delete the presentations, connect/disconnect the subject and groups.
- the findAll method of the service returns the desired type for the frontend
- the findOne method doesn't, because I think we might have to update that type. Should be discussed on the next meeting
- Added a few endpoints to the consultation controller (join, rate)
- Closes #40
=> Consultations service and more

src/consultations/consultations.controller.ts, src/consultations/participation.service.ts
- POST /consultations/:id/leave
- PATCH /consultations/:id/rate
Closes #47
=> New endpoints

src/auth/authorization.guard.ts, src/auth/casl-ability.factory.ts, src/consultations/consultations.controller.ts, src/consultations/consultations.service.ts, src/seed/seeder.service.ts, src/users/users.service.ts, src/utils/FileExtensionValidator.ts, src/utils/FileMaxSizeValidator.ts, src/utils/scheduler/scheduler.service.ts
- Updated some error messages to Hungarian
- 401 and 403 to be handled from the frontend
- Disabled some eslint warnings
closes #68
=> Eng to hun error messages

src/subject/dto/CreateSubject.dto.ts, src/subject/dto/SubjectEntity.dto.ts, src/subject/dto/UpdateSubject.dto.ts, src/subject/subject.controller.ts, src/subject/subject.service.ts
- create subject dto
- update subject dto
closes #51
=> Subject dtos

postman_collection.json, src/auth/casl-ability.factory.ts, src/consultations/consultations.controller.ts, src/consultations/consultations.service.ts, src/consultations/dto/CreateConsultation.dto.ts, src/consultations/dto/UpdateConsultation.dto.ts, src/groups/dto/UpdateGroup.dto.ts, src/groups/groups.controller.ts, src/groups/groups.service.ts, src/subject/subject.controller.ts, src/users/users.controller.ts
- Unique error messages for everything I could find
- Errors are handled in the casl factory or in the controllers
If you make endpoints please follow the same error handling pattern.
closes #53
=> Advanced error handling

src/groups/groups.controller.ts, src/groups/groups.service.ts, src/users/users.controller.ts, src/users/users.service.ts
=> Add group and user search

src/consultations/consultations.controller.ts, src/consultations/consultations.service.ts, src/consultations/dto/ConsultationEntity.dto.ts, src/consultations/dto/CreateConsultation.dto.ts, src/seed/data/consultations.ts
=> Prevent rating before consultation started

src/auth/casl-ability.factory.ts, src/consultations/consultations.controller.ts
=> Consultation join permission

prisma/migrations/20230127125008_unique_groupname_optional_desc/migration.sql, prisma/schema.prisma, src/consultations/dto/ConsultationEntity.dto.ts, src/groups/groups.controller.ts, src/groups/groups.service.ts
see commit messages
Closes #81
=> Misc changes

src/users/dto/PublicUser.dto.ts, src/users/dto/UserDetails.ts, src/users/dto/UserPreview.dto.ts, src/users/users.controller.ts, src/users/users.service.ts
=> User endpoint return types

src/auth/casl-ability.factory.ts
=> prevent users from joining consultations for other groups

src/groups/groups.controller.ts, src/groups/groups.service.ts
=> Group controller new endpoints

src/groups/groups.controller.ts
=> Prevent removing admins or owner from group

src/users/dto/UserDetails.ts, src/users/dto/UserPreview.dto.ts, src/users/users.controller.ts, src/users/users.service.ts
Changed a few stuff now that we roughly know what we want to show on the user page.
Related to https://github.com/kir-dev/konzisite-frontend/pull/79
=> User service changes

src/consultations/consultations.service.ts, src/consultations/dto/ConsultationDetails.dto.ts, src/consultations/dto/ConsultationPreview.dto.ts, src/groups/dto/GroupDetails.dto.ts, src/groups/dto/GroupPreview.dto.ts, src/groups/groups.service.ts, src/users/users.service.ts, src/utils/publicUserProjection.ts, src/utils/removeSensitiveUserData.ts
On the user endpoints, we paid attention to not send sensitive user information, like email addresses, but this was forgotten from the other endpoints. Now I added everywhere.
Related frontend updates here: https://github.com/kir-dev/konzisite-frontend/pull/92
=> user type updates

prisma/migrations/20230213113955_request_optional_desc_and_remove_consultation_id/migration.sql, prisma/schema.prisma, src/app.module.ts, src/auth/authorization.guard.ts, src/auth/casl-ability.factory.ts, src/requests/dto/CreateRequest.dto.ts, src/requests/dto/RequestDetails.dto.ts, src/requests/dto/RequestEntity.dto.ts, src/requests/dto/RequestPreview.dto.ts, src/requests/dto/UpdateRequest.dto.ts, src/requests/requests.controller.spec.ts, src/requests/requests.controller.ts, src/requests/requests.module.ts, src/requests/requests.service.spec.ts, src/requests/requests.service.ts
=> Add consultation requests

.env.example, src/auth/auth.service.ts, src/main.ts, src/seed/seeder.ts, src/utils/scheduler/scheduler.service.ts
=> dont show debug logs in prod

Dockerfile, docker-compose.yml, package-lock.json, package.json
node_modules size: 400MB -> 180 MB
Closes #111
=> new dockerfile

src/consultations/consultations.controller.ts, src/requests/dto/RequestDetails.dto.ts, src/requests/dto/RequestPreview.dto.ts, src/requests/requests.controller.ts, src/requests/requests.service.ts
Include ConsultationPreview in details and currentUserSupports in preview
=> Consultation request fix

src/users/users.service.ts
will fix https://github.com/kir-dev/konzisite-frontend/issues/129
=> user order

src/auth/casl-ability.factory.ts, src/users/dto/UserDetails.ts, src/users/users.controller.ts, src/users/users.service.spec.ts, src/users/users.service.ts
and send the stats (which do include the private konzik) separately
related to https://github.com/kir-dev/konzisite-frontend/pull/157
=> hide private konzik from userprofile

src/consultations/dto/ConsultationEntity.dto.ts, src/groups/dto/CreateGroup.dto.ts, src/groups/dto/UpdateGroup.dto.ts, src/requests/dto/CreateRequest.dto.ts, src/requests/dto/RequestEntity.dto.ts, src/requests/dto/UpdateRequest.dto.ts
related to https://github.com/kir-dev/konzisite-frontend/pull/150
=> length validation

src/users/dto/UserDetails.ts, src/users/users.service.ts
to show on the profile page
also send stats about the number of requested konzi
Closes #144
related to https://github.com/kir-dev/konzisite-frontend/pull/201
=> Send supported requests about every user

src/auth/auth.service.ts, src/consultations/consultations.service.ts, src/groups/groups.service.ts, src/requests/requests.service.ts
- delete konzi attachment when a konzi is deleted
- some logging on create and delete operations
=> logging and more
